const db = {
    "ESTADO DE RESULTADOS": {
        "VENTAS Y/O SERVICIOS NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 784029.06,
            "TOTAL": 784029.06
        },
        "VENTAS Y/O SERVICIOS EXTRANJEROS": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "DEVOLUCIONES, DESCUENTOS Y BONIFICACIONES SOBRE VENTAS NACIONALES": {
            "PARTES RELACIONADAS": 867849.02,
            "PARTES NO RELACIONADAS": 994976.66,
            "TOTAL": 1862825.68
        },
        "DEVOLUCIONES, DESCUENTOS Y BONIFICACIONES SOBRE VENTAS AL EXTRANJERO": {
            "PARTES RELACIONADAS": 664397.65,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 664397.65
        },
        "INGRESOS NETOS": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "INVENTARIO INICIAL": 759743.87,
        "COMPRAS NETAS NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 981660.11,
            "TOTAL": 981660.11
        },
        "COMPRAS NETAS DE IMPORTACIÓN": {
            "PARTES RELACIONADAS": 729402.81,
            "PARTES NO RELACIONADAS": 779039.85,
            "TOTAL": 1508442.66
        },
        "INVENTARIO FINAL": 506279.73,
        "COSTO DE LAS MERCANCÍAS": 833977.41,
        "MANO DE OBRA": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "MAQUILAS": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 563379.91,
            "TOTAL": 563379.91
        },
        "GASTOS INDIRECTOS DE FABRICACIÓN": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "COSTO DE VENTAS Y/O SERVICIOS": {
            "TOTAL": 720525.08
        },
        "UTILIDAD BRUTA": {
            "TOTAL": 771512.72
        },
        "PÉRDIDA BRUTA": {
            "TOTAL": 515302.72
        },
        "GASTOS DE OPERACIÓN": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 664222.76,
            "TOTAL": 664222.76
        },
        "UTILIDAD DE OPERACIÓN": 525574.59,
        "PÉRDIDA DE OPERACIÓN": 818697.36,
        "INTERESES DEVENGADOS A FAVOR NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "INTERESES DEVENGADOS A FAVOR DEL EXTRANJERO": {
            "PARTES RELACIONADAS": 597324.44,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 597324.44
        },
        "INTERESES MORATORIOS A FAVOR NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "INTERESES MORATORIOS A FAVOR DEL EXTRANJERO": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 775606.07,
            "TOTAL": 775606.07
        },
        "GANANCIA CAMBIARIA": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "INTERESES DEVENGADOS A CARGO NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 826168.28,
            "TOTAL": 826168.28
        },
        "INTERESES DEVENGADOS A CARGO DEL EXTRANJERO": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 905724.47,
            "TOTAL": 905724.47
        },
        "INTERESES MORATORIOS A CARGO NACIONALES": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 735571.58,
            "TOTAL": 735571.58
        },
        "INTERESES MORATORIOS A CARGO DEL EXTRANJERO": {
            "PARTES RELACIONADAS": 824908.55,
            "PARTES NO RELACIONADAS": 728222.7,
            "TOTAL": 1553131.25
        },
        "PÉRDIDA CAMBIARIA": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "RESULTADO POR POSICIÓN MONETARIA FAVORABLE": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": 530955.58,
            "TOTAL": 530955.58
        },
        "RESULTADO POR POSICIÓN MONETARIA DESFAVORABLE": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "OTRAS OPERACIONES FINANCIERAS NACIONALES": {
            "PARTES RELACIONADAS": 729362.06,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 729362.06
        },
        "OTRAS OPERACIONES FINANCIERAS EXTRANJERAS": {
            "PARTES RELACIONADAS": null,
            "PARTES NO RELACIONADAS": null,
            "TOTAL": 0
        },
        "OTRAS OPERACIONES FINANCIERAS": 878110.64,
        "RESULTADO INTEGRAL DE FINANCIAMIENTO": 966580.75,
        "OTROS GASTOS NACIONALES": null,
        "OTROS GASTOS EXTRANJEROS": null,
        "OTROS GASTOS": 0,
        "OTROS PRODUCTOS NACIONALES": 837825.48,
        "OTROS PRODUCTOS EXTRANJEROS": null,
        "OTROS PRODUCTOS": 837825.48,
        "INGRESOS POR PARTIDAS DISCONTINUAS Y EXTRAORDINARIAS": 916118.44,
        "GASTOS POR PARTIDAS DISCONTINUAS Y EXTRAORDINARIAS": 662424.8,
        "UTILIDAD ANTES DE IMPUESTOS": 799235.42,
        "PÉRDIDA ANTES DE IMPUESTOS": 997799.36,
        "ISR": 824375.35,
        "IETU": 730122.32,
        "IMPAC": 754248.52,
        "PTU": 847075.25,
        "UTILIDAD EN PARTICIPACIÓN SUBSIDIARIA": 597357.07,
        "PÉRDIDA EN PARTICIPACIÓN SUBSIDIARIA": 642163.92,
        "EFECTOS DE REEXPRESIÓN FAVORABLES EXCEPTO RESULTADO POR POSICIÓN MONETARIA": 994336,
        "EFECTOS DE REEXPRESIÓN DESFAVORABLES EXCEPTO RESULTADO POR POSICIÓN MONETARIA": 535085.44,
        "UTILIDAD NETA": 725805.08,
        "PÉRDIDA NETA": 504426.95
    },
    "ESTADO DE POSICIÓN FINANCIERA (BALANCE)": {
        "ACTIVO": {
            "EFECTIVO EN CAJA Y DEPÓSITOS EN INSTITUCIONES DE CRÉDITO NACIONALES": 993596.66,
            "EFECTIVO EN CAJA Y DEPÓSITOS EN INSTITUCIONES DE CRÉDITO DEL EXTRANJERO": 706537.48,
            "INVERSIONES EN VALORES CON INSTITUCIONES NACIONALES (EXCEPTO ACCIONES)": 854289.38,
            "INVERSIONES EN VALORES CON INSTITUCIONES EXTRANJERAS (EXCEPTO ACCIONES)": 635541.84,
            "CUENTAS Y DOCUMENTOS POR COBRAR NACIONALES": {
                "PARTES RELACIONADAS": null,
                "PARTES NO RELACIONADAS": 772297.45,
                "TOTAL": 772297.45
            },
            "CUENTAS Y DOCUMENTOS POR COBRAR DEL EXTRANJERO": {
                "PARTES RELACIONADAS": null,
                "PARTES NO RELACIONADAS": 575730.82,
                "TOTAL": 575730.82
            },
            "CONTRIBUCIONES A FAVOR": 549695.13,
            "INVENTARIOS": 613467.07,
            "OTROS ACTIVOS CIRCULANTES": 809516.02,
            "INVERSIONES EN ACCIONES NACIONALES": null,
            "INVERSIONES EN ACCIONES DEL EXTRANJERO": 575730.82,
            "INVERSIONES EN ACCIONES (TOTAL)": 575730.82,
            "TERRENOS": 984205.53,
            "CONSTRUCCIONES": 892752.53,
            "CONSTRUCCIONES EN PROCESO": 914870.48,
            "MAQUINARIA Y EQUIPO": 717295.99,
            "MOBILIARIO Y EQUIPO DE OFICINA": 572870.67,
            "EQUIPO DE CÓMPUTO": 795740.02,
            "EQUIPO DE TRANSPORTE": 848739.98,
            "OTROS ACTIVOS FIJOS": 567528.49,
            "DEPRECIACIÓN ACUMULADA": 573151.21,
            "CARGOS Y GASTOS DIFERIDOS": 543916.51,
            "AMORTIZACIÓN ACUMULADA": 873863.32,
            "SUMA ACTIVOS": 905693.66
        },
        "PASIVO": {
            "CUENTAS Y DOCUMENTOS POR PAGAR NACIONALES": {
                "PARTES RELACIONADAS": 567307.74,
                "PARTES NO RELACIONADAS": 985427.1,
                "TOTAL": 1552734.84
            },
            "CUENTAS Y DOCUMENTOS POR PAGAR DEL EXTRANJERO": {
                "PARTES RELACIONADAS": 505940.89,
                "PARTES NO RELACIONADAS": null,
                "TOTAL": 505940.89
            },
            "CONTRIBUCIONES POR PAGAR": 562922.56,
            "ANTICIPOS DE CLIENTES": {
                "PARTES RELACIONADAS": 819842.66,
                "PARTES NO RELACIONADAS": null,
                "TOTAL": 819842.66
            },
            "APORTACIONES PARA FUTUROS AUMENTOS DE CAPITAL": 519024.27,
            "OTROS PASIVOS": 654291.31,
            "SUMA PASIVOS": 666976.88
        },
        "CAPITAL CONTABLE": {
            "CAPITAL SOCIAL PROVENIENTE DE APORTACIONES": 877707.34,
            "CAPITAL SOCIAL PROVENIENTE DE CAPITALIZACIÓN": 557008.36,
            "RESERVAS": 616966.75,
            "OTRAS CUENTAS DE CAPITAL": 600528.57,
            "APORTACIONES PARA FUTUROS AUMENTOS DE CAPITAL": 904675.7,
            "UTILIDADES ACUMULADAS": 867752.28,
            "UTILIDAD DEL EJERCICIO": 752790.85,
            "PÉRDIDAS ACUMULADAS": 936823.24,
            "PÉRDIDA DEL EJERCICIO": 853183.04,
            "EXCESO EN LA ACTUALIZACIÓN DEL CAPITAL": 507755.11,
            "INSUFICIENCIA EN LA ACTUALIZACIÓN DEL CAPITAL": 585475.14,
            "ACTUALIZACIÓN DEL CAPITAL CONTABLE": 514795.55,
            "SUMA CAPITAL CONTABLE": 760347.75,
            "SUMA PASIVO MÁS CAPITAL CONTABLE": 936860
        }
    },
    "PFAE - ESTADO DE RESULTADOS": [],
    "PFAE - ESTADO DE POSICIÓN FINANCIERA": []
}